spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:h2:file:./customerDB;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: <PASSWORD>
    driverClassName: org.h2.Driver
  jackson:
    mapper:
      accept_case_insensitive_properties: true
    property-naming-strategy: UPPER_CAMEL_CASE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    org.springframework.web: error
    com.spring-boot.auth: error
  file: auth.log

server:
  ssl:
    enabled: true
    key-alias: sampleapp
    key-store-type: PKCS12
    key-store-password: <PASSWORD>
    key-store: classpath:sslkeystore.p12
  servlet:
    context-path: /api

demoAppBaseURL: https://identitydemo.acmeinc.com
backendServerPort: 8080
frontendServerPort: 4200