spring:
  application:
    name: user-management-service
  datasource:
    password: <YOUR_CUSTOM_DATABASE_PASSWORD>
    url: jdbc:mysql://localhost:3306/customerDB
    username: root
  jackson:
    mapper:
      accept_case_insensitive_properties: true
    property-naming-strategy: UPPER_CAMEL_CASE
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.web: error
    com.spring-boot.auth: error
  file: auth.log

server:
  ssl:
    enabled: true
    key-alias: demoapp
    key-store-type: PKCS12
    key-store-password: <PASSWORD>
    key-store: classpath:<KEYSTORE_NAME>.p12
  servlet:
    context-path: /api

demoAppBaseURL: https://identitydemo.acmeinc.com
backendServerPort: 8080
frontendServerPort: 4200